/** Fait le lien entre un nom de pays tel que stocké en base (majuscules,
 *  sans accents — voir `norm_country` en SQL) et son code ISO 3166-1 alpha-2,
 *  pour en dériver l'emoji drapeau. Pas d'appel réseau ni d'image : l'emoji
 *  se rend nativement sur iOS/Android/desktop, ce qui colle à l'esprit PWA
 *  hors-ligne de l'app. */
const ISO_BY_COUNTRY: Record<string, string> = {
  FRANCE: "FR",
  ALLEMAGNE: "DE",
  ESPAGNE: "ES",
  ITALIE: "IT",
  PORTUGAL: "PT",
  "ROYAUME-UNI": "GB",
  IRLANDE: "IE",
  BELGIQUE: "BE",
  "PAYS-BAS": "NL",
  LUXEMBOURG: "LU",
  SUISSE: "CH",
  AUTRICHE: "AT",
  SUEDE: "SE",
  NORVEGE: "NO",
  DANEMARK: "DK",
  FINLANDE: "FI",
  ISLANDE: "IS",
  POLOGNE: "PL",
  TCHEQUIE: "CZ",
  SLOVAQUIE: "SK",
  HONGRIE: "HU",
  ROUMANIE: "RO",
  BULGARIE: "BG",
  GRECE: "GR",
  CROATIE: "HR",
  SERBIE: "RS",
  "BOSNIE-HERZEGOVINE": "BA",
  SLOVENIE: "SI",
  ALBANIE: "AL",
  "MACEDOINE DU NORD": "MK",
  MONTENEGRO: "ME",
  KOSOVO: "XK",
  UKRAINE: "UA",
  BIELORUSSIE: "BY",
  LITUANIE: "LT",
  LETTONIE: "LV",
  ESTONIE: "EE",
  MOLDAVIE: "MD",
  RUSSIE: "RU",
  MALTE: "MT",
  CHYPRE: "CY",
  ANDORRE: "AD",
  MONACO: "MC",
  LIECHTENSTEIN: "LI",
  "SAINT-MARIN": "SM",
  CHINE: "CN",
  JAPON: "JP",
  COREE: "KR",
  "COREE DU SUD": "KR",
  "COREE DU NORD": "KP",
  MONGOLIE: "MN",
  INDE: "IN",
  PAKISTAN: "PK",
  BANGLADESH: "BD",
  "SRI LANKA": "LK",
  NEPAL: "NP",
  BHOUTAN: "BT",
  THAILANDE: "TH",
  VIETNAM: "VN",
  CAMBODGE: "KH",
  LAOS: "LA",
  BIRMANIE: "MM",
  MALAISIE: "MY",
  SINGAPOUR: "SG",
  INDONESIE: "ID",
  PHILIPPINES: "PH",
  BRUNEI: "BN",
  "TIMOR ORIENTAL": "TL",
  KAZAKHSTAN: "KZ",
  OUZBEKISTAN: "UZ",
  TURKMENISTAN: "TM",
  KIRGHIZISTAN: "KG",
  TADJIKISTAN: "TJ",
  AFGHANISTAN: "AF",
  IRAN: "IR",
  IRAK: "IQ",
  TURQUIE: "TR",
  SYRIE: "SY",
  LIBAN: "LB",
  ISRAEL: "IL",
  JORDANIE: "JO",
  "ARABIE SAOUDITE": "SA",
  YEMEN: "YE",
  OMAN: "OM",
  "EMIRATS ARABES UNIS": "AE",
  QATAR: "QA",
  BAHREIN: "BH",
  KOWEIT: "KW",
  GEORGIE: "GE",
  ARMENIE: "AM",
  AZERBAIDJAN: "AZ",
  MALDIVES: "MV",
  MAROC: "MA",
  ALGERIE: "DZ",
  TUNISIE: "TN",
  LIBYE: "LY",
  EGYPTE: "EG",
  SOUDAN: "SD",
  "SOUDAN DU SUD": "SS",
  ETHIOPIE: "ET",
  ERYTHREE: "ER",
  DJIBOUTI: "DJ",
  SOMALIE: "SO",
  KENYA: "KE",
  OUGANDA: "UG",
  TANZANIE: "TZ",
  RWANDA: "RW",
  BURUNDI: "BI",
  "REPUBLIQUE DEMOCRATIQUE DU CONGO": "CD",
  CONGO: "CG",
  GABON: "GA",
  CAMEROUN: "CM",
  NIGERIA: "NG",
  NIGER: "NE",
  TCHAD: "TD",
  MALI: "ML",
  MAURITANIE: "MR",
  SENEGAL: "SN",
  GAMBIE: "GM",
  GUINEE: "GN",
  "GUINEE-BISSAU": "GW",
  "SIERRA LEONE": "SL",
  LIBERIA: "LR",
  "COTE D'IVOIRE": "CI",
  GHANA: "GH",
  TOGO: "TG",
  BENIN: "BJ",
  "BURKINA FASO": "BF",
  CENTRAFRIQUE: "CF",
  "GUINEE EQUATORIALE": "GQ",
  ANGOLA: "AO",
  ZAMBIE: "ZM",
  ZIMBABWE: "ZW",
  MALAWI: "MW",
  MOZAMBIQUE: "MZ",
  MADAGASCAR: "MG",
  MAURICE: "MU",
  SEYCHELLES: "SC",
  COMORES: "KM",
  NAMIBIE: "NA",
  BOTSWANA: "BW",
  "AFRIQUE DU SUD": "ZA",
  LESOTHO: "LS",
  ESWATINI: "SZ",
  "CAP-VERT": "CV",
  CANADA: "CA",
  "ETATS-UNIS": "US",
  MEXIQUE: "MX",
  GUATEMALA: "GT",
  BELIZE: "BZ",
  HONDURAS: "HN",
  SALVADOR: "SV",
  NICARAGUA: "NI",
  "COSTA RICA": "CR",
  PANAMA: "PA",
  CUBA: "CU",
  HAITI: "HT",
  "REPUBLIQUE DOMINICAINE": "DO",
  JAMAIQUE: "JM",
  BAHAMAS: "BS",
  "TRINITE-ET-TOBAGO": "TT",
  BARBADE: "BB",
  "SAINTE-LUCIE": "LC",
  GRENADE: "GD",
  DOMINIQUE: "DM",
  BRESIL: "BR",
  ARGENTINE: "AR",
  CHILI: "CL",
  URUGUAY: "UY",
  PARAGUAY: "PY",
  BOLIVIE: "BO",
  PEROU: "PE",
  EQUATEUR: "EC",
  COLOMBIE: "CO",
  VENEZUELA: "VE",
  GUYANA: "GY",
  SURINAME: "SR",
  AUSTRALIE: "AU",
  "NOUVELLE-ZELANDE": "NZ",
  "PAPOUASIE-NOUVELLE-GUINEE": "PG",
  FIDJI: "FJ",
  SAMOA: "WS",
  TONGA: "TO",
  VANUATU: "VU",
  "ILES SALOMON": "SB",
  MICRONESIE: "FM",
  PALAOS: "PW",
  NAURU: "NR",
  TUVALU: "TV",
  KIRIBATI: "KI",
  "ILES MARSHALL": "MH",
};

/** "FR" -> "🇫🇷" par substitution Unicode (indicateurs régionaux A-Z -> 🇦-🇿). */
function isoToFlagEmoji(iso: string): string {
  return iso
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
}

/** Emoji drapeau pour un nom de pays tel que stocké en base ; "" si inconnu
 *  (nom mal orthographié, pool étendu côté serveur sans mise à jour ici…). */
export function flagEmoji(countryName: string): string {
  const iso = ISO_BY_COUNTRY[countryName.trim().toUpperCase()];
  return iso ? isoToFlagEmoji(iso) : "";
}
